# Generated by Django 5.1 on 2024-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topAjudantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topAjudantes',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
    ]
